// U-Farm Multilingual Support - English, Kiswahili, Luganda
export type Language = 'en' | 'sw' | 'lg';

export const translations = {
  en: {
    appName: 'U-Farm',
    appSlogan: 'Your farming assistant',
    getStarted: 'Get Started',
    alreadyHaveAccount: 'Already have an account?',
    signIn: 'Sign In',
    createAccount: 'Create Account',
    welcome: 'Welcome',
    english: 'English',
    kiswahili: 'Kiswahili',
    luganda: 'Luganda',
    signInTitle: 'Sign In',
    createAccountTitle: 'Create Account',
    email: 'Email',
    phone: 'Phone Number',
    password: 'Password',
    fullName: 'Full Name',
    farmSize: 'Farm Size (acres)',
    cropType: 'Primary Crop',
    forgotPassword: 'Forgot Password?',
    orContinueWith: 'Or continue with',
    google: 'Google',
    apple: 'Apple',
    iAmFarmer: 'I am a Farmer',
    iAmExtensionWorker: 'I am an Extension Worker',
    termsText: 'By signing up, you agree to our Terms and Privacy Policy',
    gpsDetected: 'GPS Detected',
    location: 'Location',
    temperature: 'Temperature',
    humidity: 'Humidity',
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    farmersJournal: 'Farmer\'s Journal',
    aiChatbot: 'AI Chatbot',
    cropCalendar: 'Crop Calendar',
    premium: 'Premium',
    settings: 'Settings',
    alertsNotifications: 'Alerts & Notifications',
    home: 'Home',
    journal: 'Journal',
    calendar: 'Calendar',
    ai: 'AI',
    subscription: 'Subscription',
    myDailyJournal: 'My Daily Journal',
    addEntry: 'Add Entry',
    whatIDidToday: 'What I did today',
    uploadPhoto: 'Upload Photo',
    voiceNote: 'Voice Note',
    crop: 'Crop',
    analyzeJournal: 'Analyze my journal',
    previousEntries: 'Previous Entries',
    aiTag: 'AI Generated',
    aiPoweredCalendar: 'AI-Powered Calendar',
    aiScheduledActivities: 'AI Scheduled Activities',
    sendAlertNow: 'Send Alert Now',
    askAIReschedule: 'Ask AI to Reschedule',
    plant: 'Plant',
    harvest: 'Harvest',
    alert: 'Alert',
    aiAssistantTitle: 'U-Farm AI Assistant',
    aiAssistantSubtitle: 'Ask anything about your farm',
    takePhoto: 'Take Photo',
    uploadImage: 'Upload',
    voiceInput: 'Voice',
    typeMessage: 'Type',
    typeHere: 'Type your message...',
    send: 'Send',
    exampleQuestions: 'Try asking:',
    diagnosisExample: 'Diagnose leaf disease',
    goPremium: 'Go Premium',
    unlockFullAI: 'Unlock Full AI Power',
    basic: 'Basic',
    pro: 'Pro',
    enterprise: 'Enterprise',
    perMonth: '/mo',
    unlimitedPrompts: 'Unlimited prompts',
    unlimitedUploads: 'Unlimited uploads',
    unlimitedRecommendations: 'Unlimited recommendations',
    unlockBasic: 'Unlock Basic',
    unlockPro: 'Unlock Pro',
    unlockEnterprise: 'Unlock Enterprise',
    changePassword: 'Change Password',
    language: 'Language',
    darkMode: 'Dark Mode',
    notifications: 'Notifications',
    farmInformation: 'Farm Information',
    helpSupport: 'Help & Support',
    rateUs: 'Rate Us',
    logOut: 'Log Out',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    saveChanges: 'Save Changes',
    back: 'Back',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    done: 'Done',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
  },
  sw: {
    appName: 'U-Farm',
    appSlogan: 'Msaidizi wako wa kilimo',
    getStarted: 'Anza',
    alreadyHaveAccount: 'Unayo akaunti tayari?',
    signIn: 'Ingia',
    createAccount: 'Unda Akaunti',
    welcome: 'Karibu',
    english: 'Kiingereza',
    kiswahili: 'Kiswahili',
    luganda: 'Kiluganda',
    signInTitle: 'Ingia',
    createAccountTitle: 'Unda Akaunti',
    email: 'Barua pepe',
    phone: 'Nambari ya Simu',
    password: 'Nenosiri',
    fullName: 'Jina Kamili',
    farmSize: 'Ukubwa wa Shamba (ekari)',
    cropType: 'Mazao Kuu',
    forgotPassword: 'Umesahau Nenosiri?',
    orContinueWith: 'Au endelea na',
    google: 'Google',
    apple: 'Apple',
    iAmFarmer: 'Mimi ni Mkulima',
    iAmExtensionWorker: 'Mimi ni Afisa Ugani',
    termsText: 'Kwa kujiandikisha, unakubali Sheria na Sera yetu ya Faragha',
    gpsDetected: 'GPS Imegunduliwa',
    location: 'Mahali',
    temperature: 'Joto',
    humidity: 'Unyevu',
    goodMorning: 'Habari za asubuhi',
    goodAfternoon: 'Habari za mchana',
    goodEvening: 'Habari za jioni',
    farmersJournal: 'Jarida la Mkulima',
    aiChatbot: 'AI Chatbot',
    cropCalendar: 'Kalenda ya Mazao',
    premium: 'Premium',
    settings: 'Mipangilio',
    alertsNotifications: 'Tahadhari na Arifa',
    home: 'Nyumbani',
    journal: 'Jarida',
    calendar: 'Kalenda',
    ai: 'AI',
    subscription: 'Usajili',
    myDailyJournal: 'Jarida Langu la Kila Siku',
    addEntry: 'Ongeza Kuingia',
    whatIDidToday: 'Nilichofanya leo',
    uploadPhoto: 'Pakia Picha',
    voiceNote: 'Sauti',
    crop: 'Zao',
    analyzeJournal: 'Changanua jarida langu',
    previousEntries: 'Kuingia Kabla',
    aiTag: 'AI Imetengeneza',
    aiPoweredCalendar: 'Kalenda Inayoendeshwa na AI',
    aiScheduledActivities: 'Shughuli Zilizopangwa na AI',
    sendAlertNow: 'Tuma Tahadhari Sasa',
    askAIReschedule: 'Uliza AI Kubadilisha',
    plant: 'Panda',
    harvest: 'Vuna',
    alert: 'Tahadhari',
    aiAssistantTitle: 'Msaidizi wa U-Farm AI',
    aiAssistantSubtitle: 'Uliza chochote kuhusu shamba lako',
    takePhoto: 'Piga Picha',
    uploadImage: 'Pakia',
    voiceInput: 'Sauti',
    typeMessage: 'Andika',
    typeHere: 'Andika ujumbe wako...',
    exampleQuestions: 'Jaribu kuuliza:',
    diagnosisExample: 'Gundua ugonjwa wa jani',
    goPremium: 'Nenda Premium',
    unlockFullAI: 'Fungua Nguvu Kamili ya AI',
    basic: 'Msingi',
    pro: 'Pro',
    enterprise: 'Biashara',
    perMonth: '/mwezi',
    unlimitedPrompts: 'Maelekezo yasiyo na kikomo',
    unlimitedUploads: 'Upakiaji usio na kikomo',
    unlimitedRecommendations: 'Mapendekezo yasiyo na kikomo',
    unlockBasic: 'Fungua Msingi',
    unlockPro: 'Fungua Pro',
    unlockEnterprise: 'Fungua Biashara',
    changePassword: 'Badilisha Nenosiri',
    language: 'Lugha',
    darkMode: 'Hali ya Giza',
    notifications: 'Arifa',
    farmInformation: 'Taarifa za Shamba',
    helpSupport: 'Msaada na Usaidizi',
    rateUs: 'Tukague',
    logOut: 'Toka',
    currentPassword: 'Nenosiri la Sasa',
    newPassword: 'Nenosiri Jipya',
    confirmPassword: 'Thibitisha Nenosiri',
    saveChanges: 'Hifathi Mabadiliko',
    back: 'Rudi',
    cancel: 'Ghairi',
    save: 'Hifathi',
    delete: 'Futa',
    edit: 'Hariri',
    done: 'Maliza',
    loading: 'Inapakia...',
    error: 'Kosa',
    success: 'Mafanikio',
  },
  lg: {
    appName: 'U-Farm',
    appSlogan: 'Omuwesi wo okulima',
    getStarted: 'Tandika',
    alreadyHaveAccount: 'Olina akawunti dda?',
    signIn: 'Yingira',
    createAccount: 'Kola Akawunti',
    welcome: 'Tukusanyukidde',
    english: 'Lungereza',
    kiswahili: 'Kiswahili',
    luganda: 'Oluganda',
    signInTitle: 'Yingira',
    createAccountTitle: 'Kola Akawunti',
    email: 'Email',
    phone: 'Ennamba ya Simu',
    password: 'Akabonero',
    fullName: 'Erinnya Erijjuvu',
    farmSize: 'Obunene bwEttaka (eka)',
    cropType: 'Ebilime Ebikulu',
    forgotPassword: 'Weerabidde Akabonero?',
    orContinueWith: 'Oba weyongerere ne',
    google: 'Google',
    apple: 'Apple',
    iAmFarmer: 'Ndi Mulimi',
    iAmExtensionWorker: 'Ndi Mukugu wOkulima',
    termsText: 'Bwe kola akawunti, okiriza Enkolagana yaffe ne Policy ya Ebyama',
    gpsDetected: 'GPS Gwesigadde',
    location: 'Ekifo',
    temperature: 'Obugumu',
    humidity: 'Obutiti',
    goodMorning: 'Wasuze otya',
    goodAfternoon: 'Osiibye otya',
    goodEvening: 'Osiibye otya',
    farmersJournal: 'Ebitabo byOmulimi',
    aiChatbot: 'AI Chatbot',
    cropCalendar: 'Kalenda yEbilime',
    premium: 'Premium',
    settings: 'Enteekateeka',
    alertsNotifications: 'Okulumiriza nOkutegeeza',
    home: 'Ewaka',
    journal: 'Ebitabo',
    calendar: 'Kalenda',
    ai: 'AI',
    subscription: 'Okwewandiisa',
    myDailyJournal: 'Ebitabo Byange bya Buli Lwaki',
    addEntry: 'Gattako',
    whatIDidToday: 'Bye nnakola olwaleero',
    uploadPhoto: 'Teekawo Ekifananyi',
    voiceNote: 'Edoboozi',
    crop: 'Ekilime',
    analyzeJournal: 'Kebera ebitabo byange',
    previousEntries: 'Ebyayinzidwa Dda',
    aiTag: 'Ekyakolebwa AI',
    aiPoweredCalendar: 'Kalenda Efuuse AI',
    aiScheduledActivities: 'Ebikolwa Byategekedwa AI',
    sendAlertNow: 'Sindika Okulumiriza Kati',
    askAIReschedule: 'Buuzako AI Okukyusa',
    plant: 'Siga',
    harvest: 'Kungula',
    alert: 'Okulumiriza',
    aiAssistantTitle: 'Omuwesi wa U-Farm AI',
    aiAssistantSubtitle: 'Buza kyonna ku mmwe wo',
    takePhoto: 'Toka Ekifananyi',
    uploadImage: 'Teekawo',
    voiceInput: 'Edoboozi',
    typeMessage: 'Wandiika',
    typeHere: 'Wandiika obubaka...',
    exampleQuestions: 'Gezaako okubuza:',
    diagnosisExample: 'Kebera endwadde yekikajo',
    goPremium: 'Genda ku Premium',
    unlockFullAI: 'Ggulawo Amanyi ga AI Agamala',
    basic: 'Okusooka',
    pro: 'Pro',
    enterprise: 'Enteekateeka',
    perMonth: '/mwezi',
    unlimitedPrompts: 'Okubuuza okutagwawo',
    unlimitedUploads: 'Okuteekawo okutagwawo',
    unlimitedRecommendations: 'Okusuubiza okutagwawo',
    unlockBasic: 'Ggulawo Okusooka',
    unlockPro: 'Ggulawo Pro',
    unlockEnterprise: 'Ggulawo Enteekateeka',
    changePassword: 'Kyusa Akabonero',
    language: 'Olulimi',
    darkMode: 'Engeri yEkizikiza',
    notifications: 'Ebibalidwa',
    farmInformation: 'Amawulire gEttaka',
    helpSupport: 'Obuyambi nEnteekateeka',
    rateUs: 'Tuwalule',
    logOut: 'Fuluma',
    currentPassword: 'Akabonero kakati',
    newPassword: 'Akabonero Akapya',
    confirmPassword: 'Kakasa Akabonero',
    saveChanges: 'Kuuma Enkyukakyuka',
    back: 'Dda',
    cancel: 'Sazaamu',
    save: 'Kuuma',
    delete: 'Jjamu',
    edit: 'Kyusa',
    done: 'Kiwede',
    loading: 'Kigenda maaso...',
    error: 'Ensobi',
    success: 'Okuyisibwa',
  },
} as const;

export type Translations = typeof translations.en;

export function getTranslation(lang: Language, key: keyof Translations, params?: Record<string, string>): string {
  const langTranslations = translations[lang] as Record<string, string>;
  const enTranslations = translations.en as Record<string, string>;
  let text: string = langTranslations[key as string] || enTranslations[key as string] || key;
  if (params) {
    Object.entries(params).forEach(([paramKey, value]) => {
      text = text.replace(`{{${paramKey}}}`, value);
    });
  }
  return text;
}

export const months = {
  en: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
  sw: ['Januari', 'Februari', 'Machi', 'Aprili', 'Mei', 'Juni', 'Julai', 'Agosti', 'Septemba', 'Oktoba', 'Novemba', 'Desemba'],
  lg: ['Janwaliyo', 'Febwaliyo', 'Marisi', 'Apuli', 'Muyinga', 'Juuni', 'Julaayi', 'Agusito', 'Sebuttemba', 'Okitobba', 'Novemba', 'Desemba'],
};
